language: node_js
sudo: false

node_js:
  - "10"
  - "12"
  - "13"

git:
  depth: false

script:
  - npm test

after_success:
  - if [[ "$TRAVIS_NODE_VERSION" == 13 ]]; then npm run coveralls; fi

after_failure:
  - cat nats-streaming-server/logs/*.log