language: node_js
sudo: false

node_js:
  - "10"
  - "12"
  - "13"

git:
  depth: false

script:
  - if [[ "$TRAVIS_NODE_VERSION" == 10 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 12 ]]; then npm test; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 13 ]]; then npm test; npm run cover:coveralls; fi
